// Code generated by protoc-gen-go. DO NOT EDIT.
// source: TestScaling.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TestScaling_Scaling int32

const (
	TestScaling_NONE TestScaling_Scaling = 0
	TestScaling_WAIT TestScaling_Scaling = 1
	TestScaling_LOW  TestScaling_Scaling = 2
	TestScaling_HIGH TestScaling_Scaling = 3
)

var TestScaling_Scaling_name = map[int32]string{
	0: "NONE",
	1: "WAIT",
	2: "LOW",
	3: "HIGH",
}
var TestScaling_Scaling_value = map[string]int32{
	"NONE": 0,
	"WAIT": 1,
	"LOW":  2,
	"HIGH": 3,
}

func (x TestScaling_Scaling) String() string {
	return proto.EnumName(TestScaling_Scaling_name, int32(x))
}
func (TestScaling_Scaling) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_TestScaling_590d596cd956086a, []int{0, 0}
}

type TestScaling struct {
	State                TestScaling_Scaling `protobuf:"varint,1,opt,name=state,proto3,enum=proto.TestScaling_Scaling" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *TestScaling) Reset()         { *m = TestScaling{} }
func (m *TestScaling) String() string { return proto.CompactTextString(m) }
func (*TestScaling) ProtoMessage()    {}
func (*TestScaling) Descriptor() ([]byte, []int) {
	return fileDescriptor_TestScaling_590d596cd956086a, []int{0}
}
func (m *TestScaling) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestScaling.Unmarshal(m, b)
}
func (m *TestScaling) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestScaling.Marshal(b, m, deterministic)
}
func (dst *TestScaling) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestScaling.Merge(dst, src)
}
func (m *TestScaling) XXX_Size() int {
	return xxx_messageInfo_TestScaling.Size(m)
}
func (m *TestScaling) XXX_DiscardUnknown() {
	xxx_messageInfo_TestScaling.DiscardUnknown(m)
}

var xxx_messageInfo_TestScaling proto.InternalMessageInfo

func (m *TestScaling) GetState() TestScaling_Scaling {
	if m != nil {
		return m.State
	}
	return TestScaling_NONE
}

func init() {
	proto.RegisterType((*TestScaling)(nil), "proto.TestScaling")
	proto.RegisterEnum("proto.TestScaling_Scaling", TestScaling_Scaling_name, TestScaling_Scaling_value)
}

func init() { proto.RegisterFile("TestScaling.proto", fileDescriptor_TestScaling_590d596cd956086a) }

var fileDescriptor_TestScaling_590d596cd956086a = []byte{
	// 124 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x0c, 0x49, 0x2d, 0x2e,
	0x09, 0x4e, 0x4e, 0xcc, 0xc9, 0xcc, 0x4b, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05,
	0x53, 0x4a, 0x85, 0x5c, 0xdc, 0x48, 0x72, 0x42, 0x06, 0x5c, 0xac, 0xc5, 0x25, 0x89, 0x25, 0xa9,
	0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x7c, 0x46, 0x52, 0x10, 0xc5, 0x7a, 0xc8, 0xda, 0xa1, 0x74, 0x10,
	0x44, 0xa1, 0x92, 0x01, 0x17, 0x3b, 0x4c, 0x33, 0x07, 0x17, 0x8b, 0x9f, 0xbf, 0x9f, 0xab, 0x00,
	0x03, 0x88, 0x15, 0xee, 0xe8, 0x19, 0x22, 0xc0, 0x28, 0xc4, 0xce, 0xc5, 0xec, 0xe3, 0x1f, 0x2e,
	0xc0, 0x04, 0x12, 0xf2, 0xf0, 0x74, 0xf7, 0x10, 0x60, 0x4e, 0x62, 0x03, 0x9b, 0x69, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0x27, 0x4f, 0x8b, 0xaf, 0x95, 0x00, 0x00, 0x00,
}
