// Code generated by go-swagger; DO NOT EDIT.

package volumes_compat

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/hpc/kraken/modules/podman/models"
)

// InspectVolumeReader is a Reader for the InspectVolume structure.
type InspectVolumeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InspectVolumeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewInspectVolumeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewInspectVolumeNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewInspectVolumeInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewInspectVolumeOK creates a InspectVolumeOK with default headers values
func NewInspectVolumeOK() *InspectVolumeOK {
	return &InspectVolumeOK{}
}

/*InspectVolumeOK handles this case with default header values.

This response definition is used for both the create and inspect endpoints
*/
type InspectVolumeOK struct {
	Payload *InspectVolumeOKBody
}

func (o *InspectVolumeOK) Error() string {
	return fmt.Sprintf("[GET /volumes/{name}][%d] inspectVolumeOK  %+v", 200, o.Payload)
}

func (o *InspectVolumeOK) GetPayload() *InspectVolumeOKBody {
	return o.Payload
}

func (o *InspectVolumeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(InspectVolumeOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewInspectVolumeNotFound creates a InspectVolumeNotFound with default headers values
func NewInspectVolumeNotFound() *InspectVolumeNotFound {
	return &InspectVolumeNotFound{}
}

/*InspectVolumeNotFound handles this case with default header values.

No such volume
*/
type InspectVolumeNotFound struct {
	Payload *InspectVolumeNotFoundBody
}

func (o *InspectVolumeNotFound) Error() string {
	return fmt.Sprintf("[GET /volumes/{name}][%d] inspectVolumeNotFound  %+v", 404, o.Payload)
}

func (o *InspectVolumeNotFound) GetPayload() *InspectVolumeNotFoundBody {
	return o.Payload
}

func (o *InspectVolumeNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(InspectVolumeNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewInspectVolumeInternalServerError creates a InspectVolumeInternalServerError with default headers values
func NewInspectVolumeInternalServerError() *InspectVolumeInternalServerError {
	return &InspectVolumeInternalServerError{}
}

/*InspectVolumeInternalServerError handles this case with default header values.

Internal server error
*/
type InspectVolumeInternalServerError struct {
	Payload *InspectVolumeInternalServerErrorBody
}

func (o *InspectVolumeInternalServerError) Error() string {
	return fmt.Sprintf("[GET /volumes/{name}][%d] inspectVolumeInternalServerError  %+v", 500, o.Payload)
}

func (o *InspectVolumeInternalServerError) GetPayload() *InspectVolumeInternalServerErrorBody {
	return o.Payload
}

func (o *InspectVolumeInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(InspectVolumeInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*InspectVolumeInternalServerErrorBody inspect volume internal server error body
swagger:model InspectVolumeInternalServerErrorBody
*/
type InspectVolumeInternalServerErrorBody struct {

	// API root cause formatted for automated parsing
	// Example: API root cause
	Because string `json:"cause,omitempty"`

	// human error message, formatted for a human to read
	// Example: human error message
	Message string `json:"message,omitempty"`

	// http response code
	ResponseCode int64 `json:"response,omitempty"`
}

// Validate validates this inspect volume internal server error body
func (o *InspectVolumeInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this inspect volume internal server error body based on context it is used
func (o *InspectVolumeInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *InspectVolumeInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *InspectVolumeInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res InspectVolumeInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*InspectVolumeNotFoundBody inspect volume not found body
swagger:model InspectVolumeNotFoundBody
*/
type InspectVolumeNotFoundBody struct {

	// API root cause formatted for automated parsing
	// Example: API root cause
	Because string `json:"cause,omitempty"`

	// human error message, formatted for a human to read
	// Example: human error message
	Message string `json:"message,omitempty"`

	// http response code
	ResponseCode int64 `json:"response,omitempty"`
}

// Validate validates this inspect volume not found body
func (o *InspectVolumeNotFoundBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this inspect volume not found body based on context it is used
func (o *InspectVolumeNotFoundBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *InspectVolumeNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *InspectVolumeNotFoundBody) UnmarshalBinary(b []byte) error {
	var res InspectVolumeNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*InspectVolumeOKBody inspect volume o k body
swagger:model InspectVolumeOKBody
*/
type InspectVolumeOKBody struct {

	// Date/Time the volume was created.
	CreatedAt string `json:"CreatedAt,omitempty"`

	// Name of the volume driver used by the volume.
	// Required: true
	Driver *string `json:"Driver"`

	// User-defined key/value metadata.
	// Required: true
	Labels map[string]string `json:"Labels"`

	// Mount path of the volume on the host.
	// Required: true
	Mountpoint *string `json:"Mountpoint"`

	// Name of the volume.
	// Required: true
	Name *string `json:"Name"`

	// The driver specific options used when creating the volume.
	// Required: true
	Options map[string]string `json:"Options"`

	// The level at which the volume exists. Either `global` for cluster-wide,
	// or `local` for machine level.
	// Required: true
	Scope *string `json:"Scope"`

	// Low-level details about the volume, provided by the volume driver.
	// Details are returned as a map with key/value pairs:
	// `{"key":"value","key2":"value2"}`.
	//
	// The `Status` field is optional, and is omitted if the volume driver
	// does not support this feature.
	Status map[string]interface{} `json:"Status,omitempty"`

	// usage data
	UsageData *models.VolumeUsageData `json:"UsageData,omitempty"`
}

// Validate validates this inspect volume o k body
func (o *InspectVolumeOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDriver(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateLabels(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateMountpoint(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateOptions(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateScope(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateUsageData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *InspectVolumeOKBody) validateDriver(formats strfmt.Registry) error {

	if err := validate.Required("inspectVolumeOK"+"."+"Driver", "body", o.Driver); err != nil {
		return err
	}

	return nil
}

func (o *InspectVolumeOKBody) validateLabels(formats strfmt.Registry) error {

	if err := validate.Required("inspectVolumeOK"+"."+"Labels", "body", o.Labels); err != nil {
		return err
	}

	return nil
}

func (o *InspectVolumeOKBody) validateMountpoint(formats strfmt.Registry) error {

	if err := validate.Required("inspectVolumeOK"+"."+"Mountpoint", "body", o.Mountpoint); err != nil {
		return err
	}

	return nil
}

func (o *InspectVolumeOKBody) validateName(formats strfmt.Registry) error {

	if err := validate.Required("inspectVolumeOK"+"."+"Name", "body", o.Name); err != nil {
		return err
	}

	return nil
}

func (o *InspectVolumeOKBody) validateOptions(formats strfmt.Registry) error {

	if err := validate.Required("inspectVolumeOK"+"."+"Options", "body", o.Options); err != nil {
		return err
	}

	return nil
}

func (o *InspectVolumeOKBody) validateScope(formats strfmt.Registry) error {

	if err := validate.Required("inspectVolumeOK"+"."+"Scope", "body", o.Scope); err != nil {
		return err
	}

	return nil
}

func (o *InspectVolumeOKBody) validateUsageData(formats strfmt.Registry) error {
	if swag.IsZero(o.UsageData) { // not required
		return nil
	}

	if o.UsageData != nil {
		if err := o.UsageData.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("inspectVolumeOK" + "." + "UsageData")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this inspect volume o k body based on the context it is used
func (o *InspectVolumeOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateUsageData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *InspectVolumeOKBody) contextValidateUsageData(ctx context.Context, formats strfmt.Registry) error {

	if o.UsageData != nil {
		if err := o.UsageData.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("inspectVolumeOK" + "." + "UsageData")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *InspectVolumeOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *InspectVolumeOKBody) UnmarshalBinary(b []byte) error {
	var res InspectVolumeOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
