// Code generated by go-swagger; DO NOT EDIT.

package volumes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewLibpodRemoveVolumeParams creates a new LibpodRemoveVolumeParams object
// with the default values initialized.
func NewLibpodRemoveVolumeParams() *LibpodRemoveVolumeParams {
	var ()
	return &LibpodRemoveVolumeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLibpodRemoveVolumeParamsWithTimeout creates a new LibpodRemoveVolumeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLibpodRemoveVolumeParamsWithTimeout(timeout time.Duration) *LibpodRemoveVolumeParams {
	var ()
	return &LibpodRemoveVolumeParams{

		timeout: timeout,
	}
}

// NewLibpodRemoveVolumeParamsWithContext creates a new LibpodRemoveVolumeParams object
// with the default values initialized, and the ability to set a context for a request
func NewLibpodRemoveVolumeParamsWithContext(ctx context.Context) *LibpodRemoveVolumeParams {
	var ()
	return &LibpodRemoveVolumeParams{

		Context: ctx,
	}
}

// NewLibpodRemoveVolumeParamsWithHTTPClient creates a new LibpodRemoveVolumeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewLibpodRemoveVolumeParamsWithHTTPClient(client *http.Client) *LibpodRemoveVolumeParams {
	var ()
	return &LibpodRemoveVolumeParams{
		HTTPClient: client,
	}
}

/*LibpodRemoveVolumeParams contains all the parameters to send to the API endpoint
for the libpod remove volume operation typically these are written to a http.Request
*/
type LibpodRemoveVolumeParams struct {

	/*Force
	  force removal

	*/
	Force *bool
	/*Name
	  the name or ID of the volume

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the libpod remove volume params
func (o *LibpodRemoveVolumeParams) WithTimeout(timeout time.Duration) *LibpodRemoveVolumeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the libpod remove volume params
func (o *LibpodRemoveVolumeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the libpod remove volume params
func (o *LibpodRemoveVolumeParams) WithContext(ctx context.Context) *LibpodRemoveVolumeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the libpod remove volume params
func (o *LibpodRemoveVolumeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the libpod remove volume params
func (o *LibpodRemoveVolumeParams) WithHTTPClient(client *http.Client) *LibpodRemoveVolumeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the libpod remove volume params
func (o *LibpodRemoveVolumeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithForce adds the force to the libpod remove volume params
func (o *LibpodRemoveVolumeParams) WithForce(force *bool) *LibpodRemoveVolumeParams {
	o.SetForce(force)
	return o
}

// SetForce adds the force to the libpod remove volume params
func (o *LibpodRemoveVolumeParams) SetForce(force *bool) {
	o.Force = force
}

// WithName adds the name to the libpod remove volume params
func (o *LibpodRemoveVolumeParams) WithName(name string) *LibpodRemoveVolumeParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the libpod remove volume params
func (o *LibpodRemoveVolumeParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *LibpodRemoveVolumeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Force != nil {

		// query param force
		var qrForce bool
		if o.Force != nil {
			qrForce = *o.Force
		}
		qForce := swag.FormatBool(qrForce)
		if qForce != "" {
			if err := r.SetQueryParam("force", qForce); err != nil {
				return err
			}
		}

	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
