// Code generated by go-swagger; DO NOT EDIT.

package volumes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// LibpodCreateVolumeReader is a Reader for the LibpodCreateVolume structure.
type LibpodCreateVolumeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LibpodCreateVolumeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewLibpodCreateVolumeCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewLibpodCreateVolumeInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewLibpodCreateVolumeCreated creates a LibpodCreateVolumeCreated with default headers values
func NewLibpodCreateVolumeCreated() *LibpodCreateVolumeCreated {
	return &LibpodCreateVolumeCreated{}
}

/*LibpodCreateVolumeCreated handles this case with default header values.

Volume create response
*/
type LibpodCreateVolumeCreated struct {
	Payload *LibpodCreateVolumeCreatedBody
}

func (o *LibpodCreateVolumeCreated) Error() string {
	return fmt.Sprintf("[POST /libpod/volumes/create][%d] libpodCreateVolumeCreated  %+v", 201, o.Payload)
}

func (o *LibpodCreateVolumeCreated) GetPayload() *LibpodCreateVolumeCreatedBody {
	return o.Payload
}

func (o *LibpodCreateVolumeCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(LibpodCreateVolumeCreatedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLibpodCreateVolumeInternalServerError creates a LibpodCreateVolumeInternalServerError with default headers values
func NewLibpodCreateVolumeInternalServerError() *LibpodCreateVolumeInternalServerError {
	return &LibpodCreateVolumeInternalServerError{}
}

/*LibpodCreateVolumeInternalServerError handles this case with default header values.

Internal server error
*/
type LibpodCreateVolumeInternalServerError struct {
	Payload *LibpodCreateVolumeInternalServerErrorBody
}

func (o *LibpodCreateVolumeInternalServerError) Error() string {
	return fmt.Sprintf("[POST /libpod/volumes/create][%d] libpodCreateVolumeInternalServerError  %+v", 500, o.Payload)
}

func (o *LibpodCreateVolumeInternalServerError) GetPayload() *LibpodCreateVolumeInternalServerErrorBody {
	return o.Payload
}

func (o *LibpodCreateVolumeInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(LibpodCreateVolumeInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*LibpodCreateVolumeCreatedBody libpod create volume created body
swagger:model LibpodCreateVolumeCreatedBody
*/
type LibpodCreateVolumeCreatedBody struct {

	// Anonymous indicates that the volume was created as an anonymous
	// volume for a specific container, and will be be removed when any
	// container using it is removed.
	Anonymous bool `json:"Anonymous,omitempty"`

	// CreatedAt is the date and time the volume was created at. This is not
	// stored for older Libpod volumes; if so, it will be omitted.
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"CreatedAt,omitempty"`

	// Driver is the driver used to create the volume.
	// This will be properly implemented in a future version.
	Driver string `json:"Driver,omitempty"`

	// GID is the GID that the volume was created with.
	GID int64 `json:"GID,omitempty"`

	// Labels includes the volume's configured labels, key:value pairs that
	// can be passed during volume creation to provide information for third
	// party tools.
	Labels map[string]string `json:"Labels,omitempty"`

	// Mountpoint is the path on the host where the volume is mounted.
	Mountpoint string `json:"Mountpoint,omitempty"`

	// Name is the name of the volume.
	Name string `json:"Name,omitempty"`

	// Options is a set of options that were used when creating the volume.
	// It is presently not used.
	Options map[string]string `json:"Options,omitempty"`

	// Scope is unused and provided solely for Docker compatibility. It is
	// unconditionally set to "local".
	Scope string `json:"Scope,omitempty"`

	// Status is presently unused and provided only for Docker compatibility.
	// In the future it will be used to return information on the volume's
	// current state.
	Status map[string]string `json:"Status,omitempty"`

	// UID is the UID that the volume was created with.
	UID int64 `json:"UID,omitempty"`
}

// Validate validates this libpod create volume created body
func (o *LibpodCreateVolumeCreatedBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *LibpodCreateVolumeCreatedBody) validateCreatedAt(formats strfmt.Registry) error {
	if swag.IsZero(o.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("libpodCreateVolumeCreated"+"."+"CreatedAt", "body", "date-time", o.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this libpod create volume created body based on context it is used
func (o *LibpodCreateVolumeCreatedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *LibpodCreateVolumeCreatedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *LibpodCreateVolumeCreatedBody) UnmarshalBinary(b []byte) error {
	var res LibpodCreateVolumeCreatedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*LibpodCreateVolumeInternalServerErrorBody libpod create volume internal server error body
swagger:model LibpodCreateVolumeInternalServerErrorBody
*/
type LibpodCreateVolumeInternalServerErrorBody struct {

	// API root cause formatted for automated parsing
	// Example: API root cause
	Because string `json:"cause,omitempty"`

	// human error message, formatted for a human to read
	// Example: human error message
	Message string `json:"message,omitempty"`

	// http response code
	ResponseCode int64 `json:"response,omitempty"`
}

// Validate validates this libpod create volume internal server error body
func (o *LibpodCreateVolumeInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this libpod create volume internal server error body based on context it is used
func (o *LibpodCreateVolumeInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *LibpodCreateVolumeInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *LibpodCreateVolumeInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res LibpodCreateVolumeInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
