// Code generated by go-swagger; DO NOT EDIT.

package volumes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/hpc/kraken/modules/podman/models"
)

// LibpodListVolumesReader is a Reader for the LibpodListVolumes structure.
type LibpodListVolumesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LibpodListVolumesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLibpodListVolumesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewLibpodListVolumesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewLibpodListVolumesOK creates a LibpodListVolumesOK with default headers values
func NewLibpodListVolumesOK() *LibpodListVolumesOK {
	return &LibpodListVolumesOK{}
}

/*LibpodListVolumesOK handles this case with default header values.

Volume list
*/
type LibpodListVolumesOK struct {
	Payload []*models.Volume
}

func (o *LibpodListVolumesOK) Error() string {
	return fmt.Sprintf("[GET /libpod/volumes/json][%d] libpodListVolumesOK  %+v", 200, o.Payload)
}

func (o *LibpodListVolumesOK) GetPayload() []*models.Volume {
	return o.Payload
}

func (o *LibpodListVolumesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLibpodListVolumesInternalServerError creates a LibpodListVolumesInternalServerError with default headers values
func NewLibpodListVolumesInternalServerError() *LibpodListVolumesInternalServerError {
	return &LibpodListVolumesInternalServerError{}
}

/*LibpodListVolumesInternalServerError handles this case with default header values.

Internal server error
*/
type LibpodListVolumesInternalServerError struct {
	Payload *LibpodListVolumesInternalServerErrorBody
}

func (o *LibpodListVolumesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /libpod/volumes/json][%d] libpodListVolumesInternalServerError  %+v", 500, o.Payload)
}

func (o *LibpodListVolumesInternalServerError) GetPayload() *LibpodListVolumesInternalServerErrorBody {
	return o.Payload
}

func (o *LibpodListVolumesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(LibpodListVolumesInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*LibpodListVolumesInternalServerErrorBody libpod list volumes internal server error body
swagger:model LibpodListVolumesInternalServerErrorBody
*/
type LibpodListVolumesInternalServerErrorBody struct {

	// API root cause formatted for automated parsing
	// Example: API root cause
	Because string `json:"cause,omitempty"`

	// human error message, formatted for a human to read
	// Example: human error message
	Message string `json:"message,omitempty"`

	// http response code
	ResponseCode int64 `json:"response,omitempty"`
}

// Validate validates this libpod list volumes internal server error body
func (o *LibpodListVolumesInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this libpod list volumes internal server error body based on context it is used
func (o *LibpodListVolumesInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *LibpodListVolumesInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *LibpodListVolumesInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res LibpodListVolumesInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
