// Code generated by go-swagger; DO NOT EDIT.

package containers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LibpodGenerateSystemdReader is a Reader for the LibpodGenerateSystemd structure.
type LibpodGenerateSystemdReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LibpodGenerateSystemdReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLibpodGenerateSystemdOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewLibpodGenerateSystemdInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewLibpodGenerateSystemdOK creates a LibpodGenerateSystemdOK with default headers values
func NewLibpodGenerateSystemdOK() *LibpodGenerateSystemdOK {
	return &LibpodGenerateSystemdOK{}
}

/*LibpodGenerateSystemdOK handles this case with default header values.

no error
*/
type LibpodGenerateSystemdOK struct {
	Payload map[string]string
}

func (o *LibpodGenerateSystemdOK) Error() string {
	return fmt.Sprintf("[GET /libpod/generate/{name:.*}/systemd][%d] libpodGenerateSystemdOK  %+v", 200, o.Payload)
}

func (o *LibpodGenerateSystemdOK) GetPayload() map[string]string {
	return o.Payload
}

func (o *LibpodGenerateSystemdOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLibpodGenerateSystemdInternalServerError creates a LibpodGenerateSystemdInternalServerError with default headers values
func NewLibpodGenerateSystemdInternalServerError() *LibpodGenerateSystemdInternalServerError {
	return &LibpodGenerateSystemdInternalServerError{}
}

/*LibpodGenerateSystemdInternalServerError handles this case with default header values.

Internal server error
*/
type LibpodGenerateSystemdInternalServerError struct {
	Payload *LibpodGenerateSystemdInternalServerErrorBody
}

func (o *LibpodGenerateSystemdInternalServerError) Error() string {
	return fmt.Sprintf("[GET /libpod/generate/{name:.*}/systemd][%d] libpodGenerateSystemdInternalServerError  %+v", 500, o.Payload)
}

func (o *LibpodGenerateSystemdInternalServerError) GetPayload() *LibpodGenerateSystemdInternalServerErrorBody {
	return o.Payload
}

func (o *LibpodGenerateSystemdInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(LibpodGenerateSystemdInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*LibpodGenerateSystemdInternalServerErrorBody libpod generate systemd internal server error body
swagger:model LibpodGenerateSystemdInternalServerErrorBody
*/
type LibpodGenerateSystemdInternalServerErrorBody struct {

	// API root cause formatted for automated parsing
	// Example: API root cause
	Because string `json:"cause,omitempty"`

	// human error message, formatted for a human to read
	// Example: human error message
	Message string `json:"message,omitempty"`

	// http response code
	ResponseCode int64 `json:"response,omitempty"`
}

// Validate validates this libpod generate systemd internal server error body
func (o *LibpodGenerateSystemdInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this libpod generate systemd internal server error body based on context it is used
func (o *LibpodGenerateSystemdInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *LibpodGenerateSystemdInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *LibpodGenerateSystemdInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res LibpodGenerateSystemdInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
