// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// CgroupMode CgroupMode represents cgroup mode in the container.
//
// swagger:model CgroupMode
type CgroupMode string

// Validate validates this cgroup mode
func (m CgroupMode) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this cgroup mode based on context it is used
func (m CgroupMode) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
