// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// ChangeType ChangeType represents the change type.
//
// swagger:model ChangeType
type ChangeType int64

// Validate validates this change type
func (m ChangeType) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this change type based on context it is used
func (m ChangeType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
