// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// NetworkInspectReport NetworkInspectReport describes the results from inspect networks
//
// swagger:model NetworkInspectReport
type NetworkInspectReport map[string]interface{}

// Validate validates this network inspect report
func (m NetworkInspectReport) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this network inspect report based on context it is used
func (m NetworkInspectReport) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
