// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Policy Policy denotes a seccomp policy.
//
// swagger:model Policy
type Policy int64

// Validate validates this policy
func (m Policy) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this policy based on context it is used
func (m Policy) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
